-- liquibase formatted sql

-- changeset postgres:1
CREATE TABLE users
(
    id            BIGINT generated by default as identity primary key,
    telegram_id   BIGINT   NOT NULL,
    telegram_nick TEXT,
    first_name    TEXT,
    last_name     TEXT,
    phone_number  TEXT,
    car_number    TEXT,
    email         TEXT,
    address       TEXT,
    shelter_type  SMALLINT,-- enum ShelterType
    user_type     SMALLINT NOT NULL,-- enum UserType
    user_status   SMALLINT NOT NULL -- enum UserStatus
);

CREATE TABLE pets
(
    id            BIGINT generated by default as identity primary key,
    pet_type      SMALLINT NOT NULL,-- enum PetType
    pet_name      TEXT NOT NULL,
    color         TEXT,
    gender        SMALLINT NOT NULL,-- enum Gender
    breed         TEXT
);

CREATE TABLE adopters
(
    id         BIGINT generated by default as identity primary key,
    user_id    BIGINT NOT NULL,
    pet_id     BIGINT NOT NULL
);

CREATE TABLE reports
(
    id                    BIGINT generated by default as identity primary key,
    user_id               BIGINT   NOT NULL,
    date_report           DATE     NOT NULL,
    status_report         SMALLINT NOT NULL, -- enum StatusReport
    date_end_of_probation DATE,
    link_picture          BYTEA,
    report_text           TEXT
);

CREATE TABLE dialogs
(
    id           BIGINT generated by default as identity primary key,
    guest_id     BIGINT NOT NULL,
    volunteer_id BIGINT,
    text_message TEXT   NOT NULL,
    date_message DATE   NOT NULL
);